FROM public.ecr.aws/lambda/python:3.9

COPY requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip install -r requirements.txt

COPY handler.py ${LAMBDA_TASK_ROOT}

# actual command will be in serverless.yml
CMD [ "handler" ]
